from bones.suppressors.function import string_signature_mutation
from bones.suppressors.function import missing_test_prefix_mutation

known_mutations = [string_signature_mutation, missing_test_prefix_mutation]